#访问端口号
server:
  port: 9090

#日志配置
#logging:
#  path: E:\logging
##  debug: true
##  level:
##    com.k.blog: debug
##    #org.springframework.web: DEBUG # 配置spring web日志级别
##    #root: DEBUG
###    org:
###      mybatis:
###        sql: INFO
##    druid:
##      sql:
##        DataSource: DEBUG
##        Connection: DEBUG
##        Statement: DEBUG
##        ResultSet: DEBUG



spring:
  #数据库
  datasource:
    name: springtbootDataSource
    url: jdbc:mysql://localhost:3306/tale?characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
    username: root
    password: kangkai
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5
    cache: false


#mybatis: #mybatis相关配置
mybatis:
    type-aliases-package: com.k.blog
#    type-handlers-package: com.example.typehandler
    configuration:
        map-underscore-to-camel-case: true
        # 自动将数据库中 a_b 映射成驼峰 aB mapUnderscoreToCamelCase: true
        default-fetch-size: 100
        default-statement-timeout: 30
